init:
pipeline:
  createDempDB:
    action: dsunit:init
    datastore: demo
    recreate: false
    config:
      driverName: mysql
      descriptor: '[username]:[password]@tcp(${dbIP.mysql}:3306)/[dbname]?parseTime=true'
      credentials: $mysqlCredentials
    admin:
      datastore: mysql
      ping: true
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(${dbIP.mysql}:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials
    scripts:
      - URL: ${appPath}/e2e/datastore/mysql/script/init.sql

  applySchema:
    action: exec:run
    target: $target
    checkError: true
    init:
      dbname: demo
    secrets:
      mydb: $mysqlCredentials
    commands:
      - export PATH=$PATH:/usr/local/bin/
      - echo 'starting loading demo schema'
      - docker exec  -i mysql_dev  mysql  -uroot -p${mydb.password} demo < ${appPath}/e2e/datastore/mysql/demo/script/schema.ddl

  populate:
    action: dsunit:prepare
    datastore: demo
    expand: true
    URL: ${appPath}/e2e/datastore/mysql/demo/snapshot

#  info:
#    action: print
#    message: $AsJSON(${populate})
