init:
  mysqlSecrets:  ${secrets.$mysqlCredentials}
pipeline:
  stop:
    services:
      action: docker:stop
      images:
        - mysql

  start:
    services:
      mysql_dev:
        action: docker:run
        image: mysql:5.6
        name: mysql_dev
        ports:
          3306: 3306
        env:
          MYSQL_ROOT_PASSWORD: ${mysqlSecrets.Password}

